spring:
  datasource:
    url: jdbc:mysql://paperplane-db.cz2y8guyqpbh.ap-northeast-2.rds.amazonaws.com:3306/paperplane_db
    username: admin
    password: paperplane54
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE


kakao:
  client-id: e1ac4ad724cbaae65c5782f85de2b5a7
  redirect-uri: http://localhost:8080/login-callback
  authorize-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  kakao-api-host: https://kapi.kakao.com
  client-secret: I1z20yPqRc4GMvYG6mzIqUOXZwR1EyLf
  user-info-uri: https://kapi.kakao.com/v2/user/me
  logout-uri: https://kauth.kakao.com/oauth/logout


