spring:
  datasource:
    url: jdbc:mysql://paperplane-db.cz2y8guyqpbh.ap-northeast-2.rds.amazonaws.com:3306/paperplane_db
    username: admin
    password: paperplane54
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

kakao:
  client-id: e1ac4ad724cbaae65c5782f85de2b5a7
  redirect-uri: http://54.180.136.222:8080/login-callback
  authorize-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  kakao-api-host: https://kapi.kakao.com
  client-secret: I1z20yPqRc4GMvYG6mzIqUOXZwR1EyLf
  user-info-uri: https://kapi.kakao.com/v2/user/me
  logout-uri: https://kauth.kakao.com/oauth/logout

aws:
  access-key: AKIAVRUVSGSDZVMI2WF5
  secret-key: 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
  region:
    static: ap-northeast-2
  s3:
    bucket: paperplane-s3-bucket

