spring:
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mysql://paperplane-db.cz2y8guyqpbh.ap-northeast-2.rds.amazonaws.com:3306/paperplane_db
    username: admin
    password: paperplane54
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region:
    static: ap-northeast-2
  s3:
    bucket: paperplane-s3-bucket
